### model
model_name_or_path: deepseek-ai/deepseek-coder-instruct
trust_remote_code: true
flash_attn: auto

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0
lora_target: all

### dataset
dataset_dir: data
dataset: xlam
template: deepseek-coder-instruct
cutoff_len: 2048
max_samples: 100000
preprocessing_num_workers: 16

### output
output_dir: saves/deepseek-coder-instruct/deepseek-coder-instruct/lora/xlam1
logging_steps: 1
save_steps: 100
plot_loss: true
report_to: none
include_num_input_tokens_seen: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 4.0
lr_scheduler_type: cosine
max_grad_norm: 1.0
warmup_steps: 30
packing: false
bf16: true
ddp_timeout: 180000000

### eval
# Add eval fields here if needed
