name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "alexapostolo/cloudbuilder"
          install: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/docker-cuda/Dockerfile
          platforms: linux/amd64
          tags: "${{ vars.DOCKER_USER }}/llamafactory:latest"
          cache-from: type=registry,ref=${{ vars.DOCKER_USER }}/llamafactory:cache
          cache-to: type=registry,ref=${{ vars.DOCKER_USER }}/llamafactory:cache,mode=max
          push: true
  